// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TargetRelative.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TargetRelative.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sensor_msgs {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* TargetRelative_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TargetRelative_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_TargetRelative_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_TargetRelative_2eproto() {
  protobuf_AddDesc_TargetRelative_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TargetRelative.proto");
  GOOGLE_CHECK(file != NULL);
  TargetRelative_descriptor_ = file->message_type(0);
  static const int TargetRelative_offsets_[16] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, time_usec_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, pos_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, pos_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, pos_z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, attitude_q_w_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, attitude_q_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, attitude_q_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, attitude_q_z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, orientation_q_w_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, orientation_q_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, orientation_q_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, orientation_q_z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, yaw_std_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, std_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, std_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, std_z_),
  };
  TargetRelative_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TargetRelative_descriptor_,
      TargetRelative::default_instance_,
      TargetRelative_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, _has_bits_[0]),
      -1,
      -1,
      sizeof(TargetRelative),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetRelative, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TargetRelative_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TargetRelative_descriptor_, &TargetRelative::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_TargetRelative_2eproto() {
  delete TargetRelative::default_instance_;
  delete TargetRelative_reflection_;
}

void protobuf_AddDesc_TargetRelative_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_TargetRelative_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024TargetRelative.proto\022\020sensor_msgs.msgs"
    "\"\312\002\n\016TargetRelative\022\021\n\ttime_usec\030\001 \002(\003\022\r"
    "\n\005pos_x\030\002 \002(\002\022\r\n\005pos_y\030\003 \002(\002\022\r\n\005pos_z\030\004 "
    "\002(\002\022\024\n\014attitude_q_w\030\005 \001(\001\022\024\n\014attitude_q_"
    "x\030\006 \001(\001\022\024\n\014attitude_q_y\030\007 \001(\001\022\024\n\014attitud"
    "e_q_z\030\010 \001(\001\022\027\n\017orientation_q_w\030\t \001(\001\022\027\n\017"
    "orientation_q_x\030\n \001(\001\022\027\n\017orientation_q_y"
    "\030\013 \001(\001\022\027\n\017orientation_q_z\030\014 \001(\001\022\017\n\007yaw_s"
    "td\030\r \001(\002\022\r\n\005std_x\030\016 \001(\002\022\r\n\005std_y\030\017 \001(\002\022\r"
    "\n\005std_z\030\020 \001(\002", 373);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TargetRelative.proto", &protobuf_RegisterTypes);
  TargetRelative::default_instance_ = new TargetRelative();
  TargetRelative::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TargetRelative_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TargetRelative_2eproto {
  StaticDescriptorInitializer_TargetRelative_2eproto() {
    protobuf_AddDesc_TargetRelative_2eproto();
  }
} static_descriptor_initializer_TargetRelative_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TargetRelative::kTimeUsecFieldNumber;
const int TargetRelative::kPosXFieldNumber;
const int TargetRelative::kPosYFieldNumber;
const int TargetRelative::kPosZFieldNumber;
const int TargetRelative::kAttitudeQWFieldNumber;
const int TargetRelative::kAttitudeQXFieldNumber;
const int TargetRelative::kAttitudeQYFieldNumber;
const int TargetRelative::kAttitudeQZFieldNumber;
const int TargetRelative::kOrientationQWFieldNumber;
const int TargetRelative::kOrientationQXFieldNumber;
const int TargetRelative::kOrientationQYFieldNumber;
const int TargetRelative::kOrientationQZFieldNumber;
const int TargetRelative::kYawStdFieldNumber;
const int TargetRelative::kStdXFieldNumber;
const int TargetRelative::kStdYFieldNumber;
const int TargetRelative::kStdZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TargetRelative::TargetRelative()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sensor_msgs.msgs.TargetRelative)
}

void TargetRelative::InitAsDefaultInstance() {
}

TargetRelative::TargetRelative(const TargetRelative& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:sensor_msgs.msgs.TargetRelative)
}

void TargetRelative::SharedCtor() {
  _cached_size_ = 0;
  time_usec_ = GOOGLE_LONGLONG(0);
  pos_x_ = 0;
  pos_y_ = 0;
  pos_z_ = 0;
  attitude_q_w_ = 0;
  attitude_q_x_ = 0;
  attitude_q_y_ = 0;
  attitude_q_z_ = 0;
  orientation_q_w_ = 0;
  orientation_q_x_ = 0;
  orientation_q_y_ = 0;
  orientation_q_z_ = 0;
  yaw_std_ = 0;
  std_x_ = 0;
  std_y_ = 0;
  std_z_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TargetRelative::~TargetRelative() {
  // @@protoc_insertion_point(destructor:sensor_msgs.msgs.TargetRelative)
  SharedDtor();
}

void TargetRelative::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TargetRelative::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TargetRelative::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TargetRelative_descriptor_;
}

const TargetRelative& TargetRelative::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TargetRelative_2eproto();
  return *default_instance_;
}

TargetRelative* TargetRelative::default_instance_ = NULL;

TargetRelative* TargetRelative::New(::google::protobuf::Arena* arena) const {
  TargetRelative* n = new TargetRelative;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TargetRelative::Clear() {
// @@protoc_insertion_point(message_clear_start:sensor_msgs.msgs.TargetRelative)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(TargetRelative, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<TargetRelative*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    ZR_(time_usec_, pos_z_);
  }
  if (_has_bits_[8 / 32] & 65280u) {
    ZR_(yaw_std_, std_z_);
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool TargetRelative::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sensor_msgs.msgs.TargetRelative)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 time_usec = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &time_usec_)));
          set_has_time_usec();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_pos_x;
        break;
      }

      // required float pos_x = 2;
      case 2: {
        if (tag == 21) {
         parse_pos_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pos_x_)));
          set_has_pos_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_pos_y;
        break;
      }

      // required float pos_y = 3;
      case 3: {
        if (tag == 29) {
         parse_pos_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pos_y_)));
          set_has_pos_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_pos_z;
        break;
      }

      // required float pos_z = 4;
      case 4: {
        if (tag == 37) {
         parse_pos_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pos_z_)));
          set_has_pos_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_attitude_q_w;
        break;
      }

      // optional double attitude_q_w = 5;
      case 5: {
        if (tag == 41) {
         parse_attitude_q_w:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &attitude_q_w_)));
          set_has_attitude_q_w();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_attitude_q_x;
        break;
      }

      // optional double attitude_q_x = 6;
      case 6: {
        if (tag == 49) {
         parse_attitude_q_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &attitude_q_x_)));
          set_has_attitude_q_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(57)) goto parse_attitude_q_y;
        break;
      }

      // optional double attitude_q_y = 7;
      case 7: {
        if (tag == 57) {
         parse_attitude_q_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &attitude_q_y_)));
          set_has_attitude_q_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_attitude_q_z;
        break;
      }

      // optional double attitude_q_z = 8;
      case 8: {
        if (tag == 65) {
         parse_attitude_q_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &attitude_q_z_)));
          set_has_attitude_q_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(73)) goto parse_orientation_q_w;
        break;
      }

      // optional double orientation_q_w = 9;
      case 9: {
        if (tag == 73) {
         parse_orientation_q_w:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orientation_q_w_)));
          set_has_orientation_q_w();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(81)) goto parse_orientation_q_x;
        break;
      }

      // optional double orientation_q_x = 10;
      case 10: {
        if (tag == 81) {
         parse_orientation_q_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orientation_q_x_)));
          set_has_orientation_q_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(89)) goto parse_orientation_q_y;
        break;
      }

      // optional double orientation_q_y = 11;
      case 11: {
        if (tag == 89) {
         parse_orientation_q_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orientation_q_y_)));
          set_has_orientation_q_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(97)) goto parse_orientation_q_z;
        break;
      }

      // optional double orientation_q_z = 12;
      case 12: {
        if (tag == 97) {
         parse_orientation_q_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orientation_q_z_)));
          set_has_orientation_q_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(109)) goto parse_yaw_std;
        break;
      }

      // optional float yaw_std = 13;
      case 13: {
        if (tag == 109) {
         parse_yaw_std:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &yaw_std_)));
          set_has_yaw_std();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(117)) goto parse_std_x;
        break;
      }

      // optional float std_x = 14;
      case 14: {
        if (tag == 117) {
         parse_std_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &std_x_)));
          set_has_std_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(125)) goto parse_std_y;
        break;
      }

      // optional float std_y = 15;
      case 15: {
        if (tag == 125) {
         parse_std_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &std_y_)));
          set_has_std_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(133)) goto parse_std_z;
        break;
      }

      // optional float std_z = 16;
      case 16: {
        if (tag == 133) {
         parse_std_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &std_z_)));
          set_has_std_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sensor_msgs.msgs.TargetRelative)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sensor_msgs.msgs.TargetRelative)
  return false;
#undef DO_
}

void TargetRelative::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sensor_msgs.msgs.TargetRelative)
  // required int64 time_usec = 1;
  if (has_time_usec()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->time_usec(), output);
  }

  // required float pos_x = 2;
  if (has_pos_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->pos_x(), output);
  }

  // required float pos_y = 3;
  if (has_pos_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->pos_y(), output);
  }

  // required float pos_z = 4;
  if (has_pos_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->pos_z(), output);
  }

  // optional double attitude_q_w = 5;
  if (has_attitude_q_w()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->attitude_q_w(), output);
  }

  // optional double attitude_q_x = 6;
  if (has_attitude_q_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->attitude_q_x(), output);
  }

  // optional double attitude_q_y = 7;
  if (has_attitude_q_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->attitude_q_y(), output);
  }

  // optional double attitude_q_z = 8;
  if (has_attitude_q_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->attitude_q_z(), output);
  }

  // optional double orientation_q_w = 9;
  if (has_orientation_q_w()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->orientation_q_w(), output);
  }

  // optional double orientation_q_x = 10;
  if (has_orientation_q_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->orientation_q_x(), output);
  }

  // optional double orientation_q_y = 11;
  if (has_orientation_q_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->orientation_q_y(), output);
  }

  // optional double orientation_q_z = 12;
  if (has_orientation_q_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(12, this->orientation_q_z(), output);
  }

  // optional float yaw_std = 13;
  if (has_yaw_std()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(13, this->yaw_std(), output);
  }

  // optional float std_x = 14;
  if (has_std_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(14, this->std_x(), output);
  }

  // optional float std_y = 15;
  if (has_std_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(15, this->std_y(), output);
  }

  // optional float std_z = 16;
  if (has_std_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(16, this->std_z(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sensor_msgs.msgs.TargetRelative)
}

::google::protobuf::uint8* TargetRelative::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sensor_msgs.msgs.TargetRelative)
  // required int64 time_usec = 1;
  if (has_time_usec()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->time_usec(), target);
  }

  // required float pos_x = 2;
  if (has_pos_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->pos_x(), target);
  }

  // required float pos_y = 3;
  if (has_pos_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->pos_y(), target);
  }

  // required float pos_z = 4;
  if (has_pos_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->pos_z(), target);
  }

  // optional double attitude_q_w = 5;
  if (has_attitude_q_w()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->attitude_q_w(), target);
  }

  // optional double attitude_q_x = 6;
  if (has_attitude_q_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->attitude_q_x(), target);
  }

  // optional double attitude_q_y = 7;
  if (has_attitude_q_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->attitude_q_y(), target);
  }

  // optional double attitude_q_z = 8;
  if (has_attitude_q_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->attitude_q_z(), target);
  }

  // optional double orientation_q_w = 9;
  if (has_orientation_q_w()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->orientation_q_w(), target);
  }

  // optional double orientation_q_x = 10;
  if (has_orientation_q_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->orientation_q_x(), target);
  }

  // optional double orientation_q_y = 11;
  if (has_orientation_q_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(11, this->orientation_q_y(), target);
  }

  // optional double orientation_q_z = 12;
  if (has_orientation_q_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(12, this->orientation_q_z(), target);
  }

  // optional float yaw_std = 13;
  if (has_yaw_std()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(13, this->yaw_std(), target);
  }

  // optional float std_x = 14;
  if (has_std_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(14, this->std_x(), target);
  }

  // optional float std_y = 15;
  if (has_std_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(15, this->std_y(), target);
  }

  // optional float std_z = 16;
  if (has_std_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(16, this->std_z(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sensor_msgs.msgs.TargetRelative)
  return target;
}

int TargetRelative::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:sensor_msgs.msgs.TargetRelative)
  int total_size = 0;

  if (has_time_usec()) {
    // required int64 time_usec = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->time_usec());
  }

  if (has_pos_x()) {
    // required float pos_x = 2;
    total_size += 1 + 4;
  }

  if (has_pos_y()) {
    // required float pos_y = 3;
    total_size += 1 + 4;
  }

  if (has_pos_z()) {
    // required float pos_z = 4;
    total_size += 1 + 4;
  }

  return total_size;
}
int TargetRelative::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:sensor_msgs.msgs.TargetRelative)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required int64 time_usec = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->time_usec());

    // required float pos_x = 2;
    total_size += 1 + 4;

    // required float pos_y = 3;
    total_size += 1 + 4;

    // required float pos_z = 4;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[4 / 32] & 240u) {
    // optional double attitude_q_w = 5;
    if (has_attitude_q_w()) {
      total_size += 1 + 8;
    }

    // optional double attitude_q_x = 6;
    if (has_attitude_q_x()) {
      total_size += 1 + 8;
    }

    // optional double attitude_q_y = 7;
    if (has_attitude_q_y()) {
      total_size += 1 + 8;
    }

    // optional double attitude_q_z = 8;
    if (has_attitude_q_z()) {
      total_size += 1 + 8;
    }

  }
  if (_has_bits_[8 / 32] & 65280u) {
    // optional double orientation_q_w = 9;
    if (has_orientation_q_w()) {
      total_size += 1 + 8;
    }

    // optional double orientation_q_x = 10;
    if (has_orientation_q_x()) {
      total_size += 1 + 8;
    }

    // optional double orientation_q_y = 11;
    if (has_orientation_q_y()) {
      total_size += 1 + 8;
    }

    // optional double orientation_q_z = 12;
    if (has_orientation_q_z()) {
      total_size += 1 + 8;
    }

    // optional float yaw_std = 13;
    if (has_yaw_std()) {
      total_size += 1 + 4;
    }

    // optional float std_x = 14;
    if (has_std_x()) {
      total_size += 1 + 4;
    }

    // optional float std_y = 15;
    if (has_std_y()) {
      total_size += 1 + 4;
    }

    // optional float std_z = 16;
    if (has_std_z()) {
      total_size += 2 + 4;
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TargetRelative::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sensor_msgs.msgs.TargetRelative)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const TargetRelative* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const TargetRelative>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sensor_msgs.msgs.TargetRelative)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sensor_msgs.msgs.TargetRelative)
    MergeFrom(*source);
  }
}

void TargetRelative::MergeFrom(const TargetRelative& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sensor_msgs.msgs.TargetRelative)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time_usec()) {
      set_time_usec(from.time_usec());
    }
    if (from.has_pos_x()) {
      set_pos_x(from.pos_x());
    }
    if (from.has_pos_y()) {
      set_pos_y(from.pos_y());
    }
    if (from.has_pos_z()) {
      set_pos_z(from.pos_z());
    }
    if (from.has_attitude_q_w()) {
      set_attitude_q_w(from.attitude_q_w());
    }
    if (from.has_attitude_q_x()) {
      set_attitude_q_x(from.attitude_q_x());
    }
    if (from.has_attitude_q_y()) {
      set_attitude_q_y(from.attitude_q_y());
    }
    if (from.has_attitude_q_z()) {
      set_attitude_q_z(from.attitude_q_z());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_orientation_q_w()) {
      set_orientation_q_w(from.orientation_q_w());
    }
    if (from.has_orientation_q_x()) {
      set_orientation_q_x(from.orientation_q_x());
    }
    if (from.has_orientation_q_y()) {
      set_orientation_q_y(from.orientation_q_y());
    }
    if (from.has_orientation_q_z()) {
      set_orientation_q_z(from.orientation_q_z());
    }
    if (from.has_yaw_std()) {
      set_yaw_std(from.yaw_std());
    }
    if (from.has_std_x()) {
      set_std_x(from.std_x());
    }
    if (from.has_std_y()) {
      set_std_y(from.std_y());
    }
    if (from.has_std_z()) {
      set_std_z(from.std_z());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void TargetRelative::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sensor_msgs.msgs.TargetRelative)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TargetRelative::CopyFrom(const TargetRelative& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sensor_msgs.msgs.TargetRelative)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TargetRelative::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void TargetRelative::Swap(TargetRelative* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TargetRelative::InternalSwap(TargetRelative* other) {
  std::swap(time_usec_, other->time_usec_);
  std::swap(pos_x_, other->pos_x_);
  std::swap(pos_y_, other->pos_y_);
  std::swap(pos_z_, other->pos_z_);
  std::swap(attitude_q_w_, other->attitude_q_w_);
  std::swap(attitude_q_x_, other->attitude_q_x_);
  std::swap(attitude_q_y_, other->attitude_q_y_);
  std::swap(attitude_q_z_, other->attitude_q_z_);
  std::swap(orientation_q_w_, other->orientation_q_w_);
  std::swap(orientation_q_x_, other->orientation_q_x_);
  std::swap(orientation_q_y_, other->orientation_q_y_);
  std::swap(orientation_q_z_, other->orientation_q_z_);
  std::swap(yaw_std_, other->yaw_std_);
  std::swap(std_x_, other->std_x_);
  std::swap(std_y_, other->std_y_);
  std::swap(std_z_, other->std_z_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TargetRelative::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TargetRelative_descriptor_;
  metadata.reflection = TargetRelative_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TargetRelative

// required int64 time_usec = 1;
bool TargetRelative::has_time_usec() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void TargetRelative::set_has_time_usec() {
  _has_bits_[0] |= 0x00000001u;
}
void TargetRelative::clear_has_time_usec() {
  _has_bits_[0] &= ~0x00000001u;
}
void TargetRelative::clear_time_usec() {
  time_usec_ = GOOGLE_LONGLONG(0);
  clear_has_time_usec();
}
 ::google::protobuf::int64 TargetRelative::time_usec() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.time_usec)
  return time_usec_;
}
 void TargetRelative::set_time_usec(::google::protobuf::int64 value) {
  set_has_time_usec();
  time_usec_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.time_usec)
}

// required float pos_x = 2;
bool TargetRelative::has_pos_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void TargetRelative::set_has_pos_x() {
  _has_bits_[0] |= 0x00000002u;
}
void TargetRelative::clear_has_pos_x() {
  _has_bits_[0] &= ~0x00000002u;
}
void TargetRelative::clear_pos_x() {
  pos_x_ = 0;
  clear_has_pos_x();
}
 float TargetRelative::pos_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.pos_x)
  return pos_x_;
}
 void TargetRelative::set_pos_x(float value) {
  set_has_pos_x();
  pos_x_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.pos_x)
}

// required float pos_y = 3;
bool TargetRelative::has_pos_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void TargetRelative::set_has_pos_y() {
  _has_bits_[0] |= 0x00000004u;
}
void TargetRelative::clear_has_pos_y() {
  _has_bits_[0] &= ~0x00000004u;
}
void TargetRelative::clear_pos_y() {
  pos_y_ = 0;
  clear_has_pos_y();
}
 float TargetRelative::pos_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.pos_y)
  return pos_y_;
}
 void TargetRelative::set_pos_y(float value) {
  set_has_pos_y();
  pos_y_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.pos_y)
}

// required float pos_z = 4;
bool TargetRelative::has_pos_z() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void TargetRelative::set_has_pos_z() {
  _has_bits_[0] |= 0x00000008u;
}
void TargetRelative::clear_has_pos_z() {
  _has_bits_[0] &= ~0x00000008u;
}
void TargetRelative::clear_pos_z() {
  pos_z_ = 0;
  clear_has_pos_z();
}
 float TargetRelative::pos_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.pos_z)
  return pos_z_;
}
 void TargetRelative::set_pos_z(float value) {
  set_has_pos_z();
  pos_z_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.pos_z)
}

// optional double attitude_q_w = 5;
bool TargetRelative::has_attitude_q_w() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void TargetRelative::set_has_attitude_q_w() {
  _has_bits_[0] |= 0x00000010u;
}
void TargetRelative::clear_has_attitude_q_w() {
  _has_bits_[0] &= ~0x00000010u;
}
void TargetRelative::clear_attitude_q_w() {
  attitude_q_w_ = 0;
  clear_has_attitude_q_w();
}
 double TargetRelative::attitude_q_w() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.attitude_q_w)
  return attitude_q_w_;
}
 void TargetRelative::set_attitude_q_w(double value) {
  set_has_attitude_q_w();
  attitude_q_w_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.attitude_q_w)
}

// optional double attitude_q_x = 6;
bool TargetRelative::has_attitude_q_x() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void TargetRelative::set_has_attitude_q_x() {
  _has_bits_[0] |= 0x00000020u;
}
void TargetRelative::clear_has_attitude_q_x() {
  _has_bits_[0] &= ~0x00000020u;
}
void TargetRelative::clear_attitude_q_x() {
  attitude_q_x_ = 0;
  clear_has_attitude_q_x();
}
 double TargetRelative::attitude_q_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.attitude_q_x)
  return attitude_q_x_;
}
 void TargetRelative::set_attitude_q_x(double value) {
  set_has_attitude_q_x();
  attitude_q_x_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.attitude_q_x)
}

// optional double attitude_q_y = 7;
bool TargetRelative::has_attitude_q_y() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void TargetRelative::set_has_attitude_q_y() {
  _has_bits_[0] |= 0x00000040u;
}
void TargetRelative::clear_has_attitude_q_y() {
  _has_bits_[0] &= ~0x00000040u;
}
void TargetRelative::clear_attitude_q_y() {
  attitude_q_y_ = 0;
  clear_has_attitude_q_y();
}
 double TargetRelative::attitude_q_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.attitude_q_y)
  return attitude_q_y_;
}
 void TargetRelative::set_attitude_q_y(double value) {
  set_has_attitude_q_y();
  attitude_q_y_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.attitude_q_y)
}

// optional double attitude_q_z = 8;
bool TargetRelative::has_attitude_q_z() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void TargetRelative::set_has_attitude_q_z() {
  _has_bits_[0] |= 0x00000080u;
}
void TargetRelative::clear_has_attitude_q_z() {
  _has_bits_[0] &= ~0x00000080u;
}
void TargetRelative::clear_attitude_q_z() {
  attitude_q_z_ = 0;
  clear_has_attitude_q_z();
}
 double TargetRelative::attitude_q_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.attitude_q_z)
  return attitude_q_z_;
}
 void TargetRelative::set_attitude_q_z(double value) {
  set_has_attitude_q_z();
  attitude_q_z_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.attitude_q_z)
}

// optional double orientation_q_w = 9;
bool TargetRelative::has_orientation_q_w() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void TargetRelative::set_has_orientation_q_w() {
  _has_bits_[0] |= 0x00000100u;
}
void TargetRelative::clear_has_orientation_q_w() {
  _has_bits_[0] &= ~0x00000100u;
}
void TargetRelative::clear_orientation_q_w() {
  orientation_q_w_ = 0;
  clear_has_orientation_q_w();
}
 double TargetRelative::orientation_q_w() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.orientation_q_w)
  return orientation_q_w_;
}
 void TargetRelative::set_orientation_q_w(double value) {
  set_has_orientation_q_w();
  orientation_q_w_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.orientation_q_w)
}

// optional double orientation_q_x = 10;
bool TargetRelative::has_orientation_q_x() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void TargetRelative::set_has_orientation_q_x() {
  _has_bits_[0] |= 0x00000200u;
}
void TargetRelative::clear_has_orientation_q_x() {
  _has_bits_[0] &= ~0x00000200u;
}
void TargetRelative::clear_orientation_q_x() {
  orientation_q_x_ = 0;
  clear_has_orientation_q_x();
}
 double TargetRelative::orientation_q_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.orientation_q_x)
  return orientation_q_x_;
}
 void TargetRelative::set_orientation_q_x(double value) {
  set_has_orientation_q_x();
  orientation_q_x_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.orientation_q_x)
}

// optional double orientation_q_y = 11;
bool TargetRelative::has_orientation_q_y() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void TargetRelative::set_has_orientation_q_y() {
  _has_bits_[0] |= 0x00000400u;
}
void TargetRelative::clear_has_orientation_q_y() {
  _has_bits_[0] &= ~0x00000400u;
}
void TargetRelative::clear_orientation_q_y() {
  orientation_q_y_ = 0;
  clear_has_orientation_q_y();
}
 double TargetRelative::orientation_q_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.orientation_q_y)
  return orientation_q_y_;
}
 void TargetRelative::set_orientation_q_y(double value) {
  set_has_orientation_q_y();
  orientation_q_y_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.orientation_q_y)
}

// optional double orientation_q_z = 12;
bool TargetRelative::has_orientation_q_z() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void TargetRelative::set_has_orientation_q_z() {
  _has_bits_[0] |= 0x00000800u;
}
void TargetRelative::clear_has_orientation_q_z() {
  _has_bits_[0] &= ~0x00000800u;
}
void TargetRelative::clear_orientation_q_z() {
  orientation_q_z_ = 0;
  clear_has_orientation_q_z();
}
 double TargetRelative::orientation_q_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.orientation_q_z)
  return orientation_q_z_;
}
 void TargetRelative::set_orientation_q_z(double value) {
  set_has_orientation_q_z();
  orientation_q_z_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.orientation_q_z)
}

// optional float yaw_std = 13;
bool TargetRelative::has_yaw_std() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
void TargetRelative::set_has_yaw_std() {
  _has_bits_[0] |= 0x00001000u;
}
void TargetRelative::clear_has_yaw_std() {
  _has_bits_[0] &= ~0x00001000u;
}
void TargetRelative::clear_yaw_std() {
  yaw_std_ = 0;
  clear_has_yaw_std();
}
 float TargetRelative::yaw_std() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.yaw_std)
  return yaw_std_;
}
 void TargetRelative::set_yaw_std(float value) {
  set_has_yaw_std();
  yaw_std_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.yaw_std)
}

// optional float std_x = 14;
bool TargetRelative::has_std_x() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
void TargetRelative::set_has_std_x() {
  _has_bits_[0] |= 0x00002000u;
}
void TargetRelative::clear_has_std_x() {
  _has_bits_[0] &= ~0x00002000u;
}
void TargetRelative::clear_std_x() {
  std_x_ = 0;
  clear_has_std_x();
}
 float TargetRelative::std_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.std_x)
  return std_x_;
}
 void TargetRelative::set_std_x(float value) {
  set_has_std_x();
  std_x_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.std_x)
}

// optional float std_y = 15;
bool TargetRelative::has_std_y() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
void TargetRelative::set_has_std_y() {
  _has_bits_[0] |= 0x00004000u;
}
void TargetRelative::clear_has_std_y() {
  _has_bits_[0] &= ~0x00004000u;
}
void TargetRelative::clear_std_y() {
  std_y_ = 0;
  clear_has_std_y();
}
 float TargetRelative::std_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.std_y)
  return std_y_;
}
 void TargetRelative::set_std_y(float value) {
  set_has_std_y();
  std_y_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.std_y)
}

// optional float std_z = 16;
bool TargetRelative::has_std_z() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
void TargetRelative::set_has_std_z() {
  _has_bits_[0] |= 0x00008000u;
}
void TargetRelative::clear_has_std_z() {
  _has_bits_[0] &= ~0x00008000u;
}
void TargetRelative::clear_std_z() {
  std_z_ = 0;
  clear_has_std_z();
}
 float TargetRelative::std_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.std_z)
  return std_z_;
}
 void TargetRelative::set_std_z(float value) {
  set_has_std_z();
  std_z_ = value;
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.std_z)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace sensor_msgs

// @@protoc_insertion_point(global_scope)
