// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opticalflow.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "opticalflow.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace px4 {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* OpticalFlow_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OpticalFlow_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_opticalflow_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_opticalflow_2eproto() {
  protobuf_AddDesc_opticalflow_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "opticalflow.proto");
  GOOGLE_CHECK(file != NULL);
  OpticalFlow_descriptor_ = file->message_type(0);
  static const int OpticalFlow_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpticalFlow, time_usec_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpticalFlow, integration_time_us_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpticalFlow, integrated_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpticalFlow, integrated_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpticalFlow, quality_),
  };
  OpticalFlow_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      OpticalFlow_descriptor_,
      OpticalFlow::default_instance_,
      OpticalFlow_offsets_,
      -1,
      -1,
      -1,
      sizeof(OpticalFlow),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpticalFlow, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpticalFlow, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_opticalflow_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      OpticalFlow_descriptor_, &OpticalFlow::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_opticalflow_2eproto() {
  delete OpticalFlow::default_instance_;
  delete OpticalFlow_reflection_;
}

void protobuf_AddDesc_opticalflow_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_opticalflow_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021opticalflow.proto\022\010px4.msgs\"z\n\013Optical"
    "Flow\022\021\n\ttime_usec\030\001 \001(\003\022\033\n\023integration_t"
    "ime_us\030\002 \001(\r\022\024\n\014integrated_x\030\003 \001(\002\022\024\n\014in"
    "tegrated_y\030\004 \001(\002\022\017\n\007quality\030\005 \001(\002b\006proto"
    "3", 161);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "opticalflow.proto", &protobuf_RegisterTypes);
  OpticalFlow::default_instance_ = new OpticalFlow();
  OpticalFlow::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_opticalflow_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_opticalflow_2eproto {
  StaticDescriptorInitializer_opticalflow_2eproto() {
    protobuf_AddDesc_opticalflow_2eproto();
  }
} static_descriptor_initializer_opticalflow_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OpticalFlow::kTimeUsecFieldNumber;
const int OpticalFlow::kIntegrationTimeUsFieldNumber;
const int OpticalFlow::kIntegratedXFieldNumber;
const int OpticalFlow::kIntegratedYFieldNumber;
const int OpticalFlow::kQualityFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OpticalFlow::OpticalFlow()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:px4.msgs.OpticalFlow)
}

void OpticalFlow::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

OpticalFlow::OpticalFlow(const OpticalFlow& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:px4.msgs.OpticalFlow)
}

void OpticalFlow::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  time_usec_ = GOOGLE_LONGLONG(0);
  integration_time_us_ = 0u;
  integrated_x_ = 0;
  integrated_y_ = 0;
  quality_ = 0;
}

OpticalFlow::~OpticalFlow() {
  // @@protoc_insertion_point(destructor:px4.msgs.OpticalFlow)
  SharedDtor();
}

void OpticalFlow::SharedDtor() {
  if (this != default_instance_) {
  }
}

void OpticalFlow::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OpticalFlow::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OpticalFlow_descriptor_;
}

const OpticalFlow& OpticalFlow::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_opticalflow_2eproto();
  return *default_instance_;
}

OpticalFlow* OpticalFlow::default_instance_ = NULL;

OpticalFlow* OpticalFlow::New(::google::protobuf::Arena* arena) const {
  OpticalFlow* n = new OpticalFlow;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OpticalFlow::Clear() {
// @@protoc_insertion_point(message_clear_start:px4.msgs.OpticalFlow)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(OpticalFlow, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<OpticalFlow*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(time_usec_, quality_);

#undef ZR_HELPER_
#undef ZR_

}

bool OpticalFlow::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:px4.msgs.OpticalFlow)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 time_usec = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &time_usec_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_integration_time_us;
        break;
      }

      // optional uint32 integration_time_us = 2;
      case 2: {
        if (tag == 16) {
         parse_integration_time_us:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &integration_time_us_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_integrated_x;
        break;
      }

      // optional float integrated_x = 3;
      case 3: {
        if (tag == 29) {
         parse_integrated_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &integrated_x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_integrated_y;
        break;
      }

      // optional float integrated_y = 4;
      case 4: {
        if (tag == 37) {
         parse_integrated_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &integrated_y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(45)) goto parse_quality;
        break;
      }

      // optional float quality = 5;
      case 5: {
        if (tag == 45) {
         parse_quality:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &quality_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:px4.msgs.OpticalFlow)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:px4.msgs.OpticalFlow)
  return false;
#undef DO_
}

void OpticalFlow::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:px4.msgs.OpticalFlow)
  // optional int64 time_usec = 1;
  if (this->time_usec() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->time_usec(), output);
  }

  // optional uint32 integration_time_us = 2;
  if (this->integration_time_us() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->integration_time_us(), output);
  }

  // optional float integrated_x = 3;
  if (this->integrated_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->integrated_x(), output);
  }

  // optional float integrated_y = 4;
  if (this->integrated_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->integrated_y(), output);
  }

  // optional float quality = 5;
  if (this->quality() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->quality(), output);
  }

  // @@protoc_insertion_point(serialize_end:px4.msgs.OpticalFlow)
}

::google::protobuf::uint8* OpticalFlow::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:px4.msgs.OpticalFlow)
  // optional int64 time_usec = 1;
  if (this->time_usec() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->time_usec(), target);
  }

  // optional uint32 integration_time_us = 2;
  if (this->integration_time_us() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->integration_time_us(), target);
  }

  // optional float integrated_x = 3;
  if (this->integrated_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->integrated_x(), target);
  }

  // optional float integrated_y = 4;
  if (this->integrated_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->integrated_y(), target);
  }

  // optional float quality = 5;
  if (this->quality() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->quality(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:px4.msgs.OpticalFlow)
  return target;
}

int OpticalFlow::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:px4.msgs.OpticalFlow)
  int total_size = 0;

  // optional int64 time_usec = 1;
  if (this->time_usec() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->time_usec());
  }

  // optional uint32 integration_time_us = 2;
  if (this->integration_time_us() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->integration_time_us());
  }

  // optional float integrated_x = 3;
  if (this->integrated_x() != 0) {
    total_size += 1 + 4;
  }

  // optional float integrated_y = 4;
  if (this->integrated_y() != 0) {
    total_size += 1 + 4;
  }

  // optional float quality = 5;
  if (this->quality() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OpticalFlow::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:px4.msgs.OpticalFlow)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const OpticalFlow* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const OpticalFlow>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:px4.msgs.OpticalFlow)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:px4.msgs.OpticalFlow)
    MergeFrom(*source);
  }
}

void OpticalFlow::MergeFrom(const OpticalFlow& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:px4.msgs.OpticalFlow)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.time_usec() != 0) {
    set_time_usec(from.time_usec());
  }
  if (from.integration_time_us() != 0) {
    set_integration_time_us(from.integration_time_us());
  }
  if (from.integrated_x() != 0) {
    set_integrated_x(from.integrated_x());
  }
  if (from.integrated_y() != 0) {
    set_integrated_y(from.integrated_y());
  }
  if (from.quality() != 0) {
    set_quality(from.quality());
  }
}

void OpticalFlow::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:px4.msgs.OpticalFlow)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OpticalFlow::CopyFrom(const OpticalFlow& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:px4.msgs.OpticalFlow)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OpticalFlow::IsInitialized() const {

  return true;
}

void OpticalFlow::Swap(OpticalFlow* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OpticalFlow::InternalSwap(OpticalFlow* other) {
  std::swap(time_usec_, other->time_usec_);
  std::swap(integration_time_us_, other->integration_time_us_);
  std::swap(integrated_x_, other->integrated_x_);
  std::swap(integrated_y_, other->integrated_y_);
  std::swap(quality_, other->quality_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OpticalFlow::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OpticalFlow_descriptor_;
  metadata.reflection = OpticalFlow_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OpticalFlow

// optional int64 time_usec = 1;
void OpticalFlow::clear_time_usec() {
  time_usec_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 OpticalFlow::time_usec() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.time_usec)
  return time_usec_;
}
 void OpticalFlow::set_time_usec(::google::protobuf::int64 value) {
  
  time_usec_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.time_usec)
}

// optional uint32 integration_time_us = 2;
void OpticalFlow::clear_integration_time_us() {
  integration_time_us_ = 0u;
}
 ::google::protobuf::uint32 OpticalFlow::integration_time_us() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.integration_time_us)
  return integration_time_us_;
}
 void OpticalFlow::set_integration_time_us(::google::protobuf::uint32 value) {
  
  integration_time_us_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.integration_time_us)
}

// optional float integrated_x = 3;
void OpticalFlow::clear_integrated_x() {
  integrated_x_ = 0;
}
 float OpticalFlow::integrated_x() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.integrated_x)
  return integrated_x_;
}
 void OpticalFlow::set_integrated_x(float value) {
  
  integrated_x_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.integrated_x)
}

// optional float integrated_y = 4;
void OpticalFlow::clear_integrated_y() {
  integrated_y_ = 0;
}
 float OpticalFlow::integrated_y() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.integrated_y)
  return integrated_y_;
}
 void OpticalFlow::set_integrated_y(float value) {
  
  integrated_y_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.integrated_y)
}

// optional float quality = 5;
void OpticalFlow::clear_quality() {
  quality_ = 0;
}
 float OpticalFlow::quality() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.quality)
  return quality_;
}
 void OpticalFlow::set_quality(float value) {
  
  quality_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.quality)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace px4

// @@protoc_insertion_point(global_scope)
