// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opticalflow.proto

#ifndef PROTOBUF_opticalflow_2eproto__INCLUDED
#define PROTOBUF_opticalflow_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace px4 {
namespace msgs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_opticalflow_2eproto();
void protobuf_AssignDesc_opticalflow_2eproto();
void protobuf_ShutdownFile_opticalflow_2eproto();

class OpticalFlow;

// ===================================================================

class OpticalFlow : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:px4.msgs.OpticalFlow) */ {
 public:
  OpticalFlow();
  virtual ~OpticalFlow();

  OpticalFlow(const OpticalFlow& from);

  inline OpticalFlow& operator=(const OpticalFlow& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OpticalFlow& default_instance();

  void Swap(OpticalFlow* other);

  // implements Message ----------------------------------------------

  inline OpticalFlow* New() const { return New(NULL); }

  OpticalFlow* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OpticalFlow& from);
  void MergeFrom(const OpticalFlow& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OpticalFlow* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 time_usec = 1;
  void clear_time_usec();
  static const int kTimeUsecFieldNumber = 1;
  ::google::protobuf::int64 time_usec() const;
  void set_time_usec(::google::protobuf::int64 value);

  // optional uint32 integration_time_us = 2;
  void clear_integration_time_us();
  static const int kIntegrationTimeUsFieldNumber = 2;
  ::google::protobuf::uint32 integration_time_us() const;
  void set_integration_time_us(::google::protobuf::uint32 value);

  // optional float integrated_x = 3;
  void clear_integrated_x();
  static const int kIntegratedXFieldNumber = 3;
  float integrated_x() const;
  void set_integrated_x(float value);

  // optional float integrated_y = 4;
  void clear_integrated_y();
  static const int kIntegratedYFieldNumber = 4;
  float integrated_y() const;
  void set_integrated_y(float value);

  // optional float quality = 5;
  void clear_quality();
  static const int kQualityFieldNumber = 5;
  float quality() const;
  void set_quality(float value);

  // @@protoc_insertion_point(class_scope:px4.msgs.OpticalFlow)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 time_usec_;
  ::google::protobuf::uint32 integration_time_us_;
  float integrated_x_;
  float integrated_y_;
  float quality_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_opticalflow_2eproto();
  friend void protobuf_AssignDesc_opticalflow_2eproto();
  friend void protobuf_ShutdownFile_opticalflow_2eproto();

  void InitAsDefaultInstance();
  static OpticalFlow* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// OpticalFlow

// optional int64 time_usec = 1;
inline void OpticalFlow::clear_time_usec() {
  time_usec_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 OpticalFlow::time_usec() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.time_usec)
  return time_usec_;
}
inline void OpticalFlow::set_time_usec(::google::protobuf::int64 value) {
  
  time_usec_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.time_usec)
}

// optional uint32 integration_time_us = 2;
inline void OpticalFlow::clear_integration_time_us() {
  integration_time_us_ = 0u;
}
inline ::google::protobuf::uint32 OpticalFlow::integration_time_us() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.integration_time_us)
  return integration_time_us_;
}
inline void OpticalFlow::set_integration_time_us(::google::protobuf::uint32 value) {
  
  integration_time_us_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.integration_time_us)
}

// optional float integrated_x = 3;
inline void OpticalFlow::clear_integrated_x() {
  integrated_x_ = 0;
}
inline float OpticalFlow::integrated_x() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.integrated_x)
  return integrated_x_;
}
inline void OpticalFlow::set_integrated_x(float value) {
  
  integrated_x_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.integrated_x)
}

// optional float integrated_y = 4;
inline void OpticalFlow::clear_integrated_y() {
  integrated_y_ = 0;
}
inline float OpticalFlow::integrated_y() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.integrated_y)
  return integrated_y_;
}
inline void OpticalFlow::set_integrated_y(float value) {
  
  integrated_y_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.integrated_y)
}

// optional float quality = 5;
inline void OpticalFlow::clear_quality() {
  quality_ = 0;
}
inline float OpticalFlow::quality() const {
  // @@protoc_insertion_point(field_get:px4.msgs.OpticalFlow.quality)
  return quality_;
}
inline void OpticalFlow::set_quality(float value) {
  
  quality_ = value;
  // @@protoc_insertion_point(field_set:px4.msgs.OpticalFlow.quality)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace px4

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_opticalflow_2eproto__INCLUDED
